---

- name: test redis task
  debug: msg="clearing {{ item.key }} cache via -- redis-cli -h {{ item.value.host | default('127.0.0.1') }} -p {{ item.value.port | default(6379) }} -n {{ item.value.db | default(0) }} flushdb"
  with_dict: "{{ REDIS_CACHES | default({}) }}"
  when: REDIS_CACHES is defined and REDIS_CACHES
  tags:
    - cache

- name: complain REDIS_CACHES is not defined
  debug: msg="REDIS_CACHES is not defined! Please define. Define as empty to skeip redis clearing..."
  when: REDIS_CACHES is not defined or not REDIS_CACHES


#@TODO deprecate below in skel > 2.8 ?

- name: LEGACY - flush redis cache
  shell: redis-cli -h {{ REDIS_HOST }} -p {{ REDIS_OBJ_PORT }} -n {{ REDIS_OBJ_DB }} flushdb
  tags:
    - cache
    - cache-obj-only
  when: REDIS_CACHES is not defined or not REDIS_CACHES


- name: LEGACY - flush FPC
  shell: redis-cli -h {{ REDIS_HOST }} -p {{ REDIS_FPC_PORT }} -n {{ REDIS_FPC_DB }} flushdb
  tags:
    - cache
    - cache-fpc-only
  when: REDIS_CACHES is not defined or not REDIS_CACHES
