#!/usr/bin/env bash
main(){
  set -eo pipefail

  echo "validating deb-version-compare sorts strings"
  diff -w \
    <(printf "%s\n" "1" "2" "3" | sort -r) \
    <("$PROJECT_ROOT/bin/run" scripts/deb-version-compare.py "3" "1" "2" )
}

main "$@"
