#!/usr/bin/env bash
main(){
  set -eo pipefail

  versions=(
    1.3
    0.5
    10.7
  )

  echo "validating deb-version-compare sorts strings"
  diff -w \
    <(printf "%s\n" "${versions[@]}" | sort -r) \
    <("$PROJECT_ROOT/bin/run" scripts/deb-version-compare.py "${versions[@]}")
}

main "$@"
